const question_75=`QUESTION NO: 75 솔루션 아키텍트는 비용을 최적화하고 단일 AWS 계정에서 Amazon EC2 인스턴스의 크기를 적절하게 조정하려고 합니다. 솔루션 아키텍트는 인스턴스가 CPU, 메모리 및 네트워크 메트릭을 기반으로 최적화되었는지 확인하려고 합니다. 솔루션 설계자는 이러한 요구 사항을 충족하기 위해 어떤 단계 조합을 수행해야 합니까? (2개 선택하세요.) A. 해당 계정에 대해 AWS Business Support 또는 AWS Enterprise Support를 구매합니다. B. AWS Trusted Advisor를 켜고 "사용률이 낮은 Amazon EC2 인스턴스" 권장 사항을 검토하십시오. C. Amazon CloudWatch 에이전트를 설치하고 EC2 인스턴스에서 메모리 지표 수집을 구성합니다. D. 결과 및 최적화 권장 사항을 수신하도록 AWS 계정에서 AWS Compute Optimizer를 구성합니다. E. AWS 리전, 인스턴스 제품군 및 관심 있는 운영 체제에 대한 EC2 인스턴스 절감 계획을 생성합니다. Answer: B,D(C,D인것같음) Explanation: AWS Trusted Advisor is a service that provides real-time guidance to help users provision their resources following AWS best practices1. One of the Trusted Advisor checks is "Low Utilization Amazon EC2 Instances", which identifies EC2 instances that appear to be underutilized based on CPU, network I/O, and disk I/O metrics1. This check can help users optimize the cost and size of their EC2 instances by recommending smaller or more appropriate instance types. AWS Compute Optimizer is a service that analyzes the configuration and utilization metrics of AWS resources and generates optimization recommendations to reduce the cost and improve the performance of workloads2. Compute Optimizer supports four types of AWS resources: EC2 instances, EBS volumes, ECS services on AWS Fargate, and Lambda functions2. For EC2 instances, Compute Optimizer evaluates the vCPUs, memory, storage, and other specifications, as well as the CPU utilization, network in and out, disk read and write, and other utilization metrics of currently running instances3. It then recommends optimal instance types based on price-performance trade-offs. Option A is incorrect because purchasing AWS Business Support or AWS Enterprise Support for the account will not directly help with cost-optimization and sizing of EC2 instances. However, these support plans do provide access to more Trusted Advisor checks than the basic support plan1. Option C is incorrect because installing the Amazon CloudWatch agent and configuring memory metric collection on the EC2 instances will not provide any optimization recommendations by itself. However, memory metrics can be used by Compute Optimizer to enhance its recommendations if enabled3. Option E is incorrect because creating an EC2 Instance Savings Plan for the AWS Regions, instance families, and operating systems of interest will not help with cost-optimization and sizing of EC2 instances. Savings Plans are a flexible pricing model that offer lower prices on Amazon EC2 usage in exchange for a commitment to a consistent amount of usage for a 1- or 3-year term4. Savings Plans do not affect the configuration or utilization of EC2 instances.
GPT 3.5 says "텍스트에서 제공된 답변은 정확합니다.

Amazon EC2 인스턴스의 비용과 크기를 최적화하기 위해 솔루션 아키텍트는 다음 단계를 수행할 수 있습니다:

1. AWS Trusted Advisor를 활성화하고 ""낮은 활용도 Amazon EC2 인스턴스"" 권장 사항을 검토합니다. 이 권장 사항은 CPU, 네트워크 I/O 및 디스크 I/O 메트릭을 기반으로 활용도가 낮은 인스턴스를 식별합니다. 이 권장 사항을 따르면 솔루션 아키텍트는 비용과 성능을 최적화하기 위해 인스턴스 크기를 조정하거나 더 적합한 인스턴스 유형을 선택할 수 있습니다.

2. AWS 계정에 AWS Compute Optimizer를 구성하여 결과와 최적화 권장 사항을 받습니다. Compute Optimizer는 EC2 인스턴스의 구성 및 활용도 메트릭을 분석하고 비용을 줄이고 성능을 향상시키기 위한 권장 사항을 제공합니다. vCPUs, 메모리, 스토리지, CPU 활용도, 네트워크 입출력, 디스크 읽기 및 쓰기와 같은 요소를 평가하고 이러한 메트릭을 기반으로 최적의 인스턴스 유형을 제안합니다.

A, C, E 옵션은 잘못된 옵션입니다:

- A 옵션은 AWS Business Support 또는 AWS Enterprise Support를 구매하는 것을 제안하지만, 이러한 지원 계획은 EC2 인스턴스의 비용 최적화와 크기 조정에 직접 도움"`;